using System.Security.Cryptography;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Phichat.Application.Common.Exceptions;
using Phichat.Application.DTOs.Keys;
using Phichat.Application.Security;
using Phichat.Application.Validators.Keys;
using Phichat.Domain.Entities;
using Phichat.Infrastructure.Data;
using Phichat.Infrastructure.Security;
using Phichat.Infrastructure.Services;

namespace Phichat.Tests;

public class IdentityKeyMathTests
{
    // Generated by WebCrypto (crypto.subtle.exportKey('spki', ...)) with its key id computed in JS.
    private const string WebCryptoSpki = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEk7h+c7YTiHxsFNqMfy4fevsueBzt4xdOZXxUAu2EdTuoBU1EWVIrOcXOEMazXyI5c/ck/g27VFeF2wFssxiyOA==";
    private const string WebCryptoKeyId = "l4etvG07LepjReOPMcd4cQ";
    private const string WebCryptoP384Spki = "MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEGSbwt3/PWG8AnIZ5GCvFxef1Al2qR99DgfFdhFJhEm2IzspFGwLKi2+6X9/kNLZiA5g1Ejr7KacST7nmATGeS6kP9pHKFQVTT+CwUCP6kNiUajYhHqoB0BcfF1dMbRGU";

    [Fact]
    public void Accepts_WebCrypto_key_and_computes_the_same_key_id()
    {
        var spki = IdentityKeyMath.ParseP256PublicKey(WebCryptoSpki);

        Assert.NotNull(spki);
        Assert.Equal(WebCryptoKeyId, IdentityKeyMath.KeyIdOf(spki!));
        Assert.True(EncryptedMessageFormat.IsValidKeyId(WebCryptoKeyId));
    }

    [Fact]
    public void Accepts_dotnet_generated_P256_key()
    {
        using var ecdh = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);
        var base64 = Convert.ToBase64String(ecdh.ExportSubjectPublicKeyInfo());

        Assert.NotNull(IdentityKeyMath.ParseP256PublicKey(base64));
    }

    [Theory]
    [InlineData(WebCryptoP384Spki)]                  // other curve
    [InlineData("not base64!")]
    [InlineData("AAAA")]
    [InlineData("")]
    public void Rejects_keys_that_are_not_P256(string value)
    {
        Assert.Null(IdentityKeyMath.ParseP256PublicKey(value));
    }

    [Fact]
    public void Rejects_point_not_on_the_curve()
    {
        var bytes = Convert.FromBase64String(WebCryptoSpki);
        bytes[^1] ^= 0x01;

        Assert.Null(IdentityKeyMath.ParseP256PublicKey(Convert.ToBase64String(bytes)));
    }

    [Fact]
    public void Rejects_trailing_bytes()
    {
        var bytes = Convert.FromBase64String(WebCryptoSpki).Append((byte)0).ToArray();

        Assert.Null(IdentityKeyMath.ParseP256PublicKey(Convert.ToBase64String(bytes)));
    }
}

public class EncryptedMessageFormatTests
{
    private const string A = "l4etvG07LepjReOPMcd4cQ";
    private const string B = "AAAAAAAAAAAAAAAAAAAAAA";
    private static readonly string Payload = Convert.ToBase64String(new byte[40]);

    [Fact]
    public void Parses_key_ids()
    {
        Assert.True(EncryptedMessageFormat.TryParse($"v2:{A}:{B}:{Payload}", out var sender, out var recipient));
        Assert.Equal(A, sender);
        Assert.Equal(B, recipient);
    }

    [Theory]
    [InlineData("")]
    [InlineData("plain base64 from the old format")]
    [InlineData("v1:l4etvG07LepjReOPMcd4cQ:AAAAAAAAAAAAAAAAAAAAAA:AAAA")]
    [InlineData("v2:short:AAAAAAAAAAAAAAAAAAAAAA:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")]
    [InlineData("v2:l4etvG07LepjReOPMcd4cQ:AAAAAAAAAAAAAAAAAAAAAA:AAAA")]         // shorter than IV + tag
    [InlineData("v2:l4etvG07LepjReOPMcd4cQ:AAAAAAAAAAAAAAAAAAAAAA:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")] // bad base64 length
    public void Rejects_malformed_bodies(string body)
    {
        Assert.False(EncryptedMessageFormat.TryParse(body, out _, out _));
    }
}

public class KeyBackupValidatorTests
{
    private static KeyBackupDto Valid() => new()
    {
        Ciphertext = Convert.ToBase64String(new byte[150]),
        Salt = Convert.ToBase64String(new byte[16]),
        Iv = Convert.ToBase64String(new byte[12]),
        Kdf = KeyRules.BackupKdf,
        Iterations = 600_000
    };

    [Fact]
    public void Accepts_a_valid_backup() => Assert.True(new KeyBackupValidator().Validate(Valid()).IsValid);

    [Fact]
    public void Rejects_weak_kdf_settings()
    {
        var weak = Valid();
        weak.Iterations = 1000;
        Assert.False(new KeyBackupValidator().Validate(weak).IsValid);

        var other = Valid();
        other.Kdf = "MD5";
        Assert.False(new KeyBackupValidator().Validate(other).IsValid);

        var badIv = Valid();
        badIv.Iv = Convert.ToBase64String(new byte[8]);
        Assert.False(new KeyBackupValidator().Validate(badIv).IsValid);
    }
}

/// <summary>Runs the service against SQLite so ExecuteUpdate and the filtered unique index are real.</summary>
public sealed class IdentityKeyServiceTests : IDisposable
{
    private readonly SqliteConnection _connection;
    private readonly AppDbContext _db;
    private readonly IdentityKeyService _service;
    private readonly Guid _alice = Guid.NewGuid();
    private readonly Guid _bob = Guid.NewGuid();

    public IdentityKeyServiceTests()
    {
        _connection = new SqliteConnection("DataSource=:memory:");
        _connection.Open();

        _db = new AppDbContext(new DbContextOptionsBuilder<AppDbContext>().UseSqlite(_connection).Options);
        _db.Database.EnsureCreated();

        _db.Users.AddRange(
            new User { Id = _alice, Username = "alice", PasswordHash = "x" },
            new User { Id = _bob, Username = "bob", PasswordHash = "x" });
        _db.SaveChanges();

        _service = new IdentityKeyService(_db);
    }

    public void Dispose()
    {
        _db.Dispose();
        _connection.Dispose();
    }

    private static PublishIdentityKeyRequest NewKeyRequest()
    {
        using var ecdh = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);
        return new PublishIdentityKeyRequest
        {
            PublicKey = Convert.ToBase64String(ecdh.ExportSubjectPublicKeyInfo()),
            Backup = new KeyBackupDto
            {
                Ciphertext = Convert.ToBase64String(RandomNumberGenerator.GetBytes(150)),
                Salt = Convert.ToBase64String(RandomNumberGenerator.GetBytes(16)),
                Iv = Convert.ToBase64String(RandomNumberGenerator.GetBytes(12)),
                Kdf = KeyRules.BackupKdf,
                Iterations = 600_000
            }
        };
    }

    private static string Body(string senderKeyId, string recipientKeyId) =>
        $"v2:{senderKeyId}:{recipientKeyId}:{Convert.ToBase64String(new byte[40])}";

    [Fact]
    public async Task Create_publishes_once()
    {
        var request = NewKeyRequest();
        var created = await _service.CreateAsync(_alice, request);

        var mine = await _service.GetMyKeyAsync(_alice);
        Assert.Equal(created.KeyId, mine!.KeyId);
        Assert.Equal(request.Backup.Ciphertext, mine.Backup.Ciphertext);

        var second = await Assert.ThrowsAsync<ConflictException>(() => _service.CreateAsync(_alice, NewKeyRequest()));
        Assert.Equal("identity_key_exists", second.Code);
    }

    [Fact]
    public async Task Create_rejects_invalid_public_key()
    {
        var request = NewKeyRequest();
        request.PublicKey = "AAAA";

        var error = await Assert.ThrowsAsync<BadRequestException>(() => _service.CreateAsync(_alice, request));
        Assert.Equal("invalid_public_key", error.Code);
    }

    [Fact]
    public async Task Replace_revokes_the_old_key_and_drops_its_backup()
    {
        var first = await _service.CreateAsync(_alice, NewKeyRequest());
        var second = await _service.ReplaceAsync(_alice, NewKeyRequest());

        Assert.NotEqual(first.KeyId, second.KeyId);
        Assert.Equal(second.KeyId, (await _service.GetActiveKeyAsync(_alice)).KeyId);

        // Peers can still fetch the old public key to read earlier messages.
        var old = await _service.GetKeyAsync(_alice, first.KeyId);
        Assert.NotNull(old.RevokedAtUtc);

        var row = await _db.UserIdentityKeys.AsNoTracking().SingleAsync(k => k.KeyId == first.KeyId);
        Assert.Null(row.BackupCiphertext);
        Assert.Equal(1, await _db.UserIdentityKeys.CountAsync(k => k.UserId == _alice && k.RevokedAtUtc == null));
    }

    [Fact]
    public async Task Replace_cannot_republish_a_used_key()
    {
        var request = NewKeyRequest();
        await _service.CreateAsync(_alice, request);

        var error = await Assert.ThrowsAsync<ConflictException>(() => _service.ReplaceAsync(_alice, request));
        Assert.Equal("identity_key_conflict", error.Code);

        // The failed replace was rolled back: the original key is still active.
        Assert.NotNull(await _service.GetMyKeyAsync(_alice));
    }

    [Fact]
    public async Task UpdateBackup_requires_the_active_key_id()
    {
        var key = await _service.CreateAsync(_alice, NewKeyRequest());
        var backup = NewKeyRequest().Backup;

        await _service.UpdateBackupAsync(_alice, new UpdateKeyBackupRequest { KeyId = key.KeyId, Backup = backup });
        Assert.Equal(backup.Ciphertext, (await _service.GetMyKeyAsync(_alice))!.Backup.Ciphertext);

        var stale = await Assert.ThrowsAsync<ConflictException>(() => _service.UpdateBackupAsync(_alice,
            new UpdateKeyBackupRequest { KeyId = "AAAAAAAAAAAAAAAAAAAAAA", Backup = backup }));
        Assert.Equal("identity_key_changed", stale.Code);
    }

    [Fact]
    public async Task Missing_keys_are_not_found()
    {
        Assert.Null(await _service.GetMyKeyAsync(_alice));

        var error = await Assert.ThrowsAsync<NotFoundException>(() => _service.GetActiveKeyAsync(_bob));
        Assert.Equal("no_identity_key", error.Code);
    }

    [Fact]
    public async Task Message_must_use_both_active_keys()
    {
        var a = await _service.CreateAsync(_alice, NewKeyRequest());

        var noKey = await Assert.ThrowsAsync<ConflictException>(() =>
            _service.EnsureMessageKeysAsync(_alice, _bob, Body(a.KeyId, a.KeyId)));
        Assert.Equal("recipient_no_key", noKey.Code);

        var b = await _service.CreateAsync(_bob, NewKeyRequest());
        await _service.EnsureMessageKeysAsync(_alice, _bob, Body(a.KeyId, b.KeyId));

        // Messages to yourself use your own key on both sides.
        await _service.EnsureMessageKeysAsync(_alice, _alice, Body(a.KeyId, a.KeyId));

        var swapped = await Assert.ThrowsAsync<ConflictException>(() =>
            _service.EnsureMessageKeysAsync(_alice, _bob, Body(b.KeyId, a.KeyId)));
        Assert.Equal("sender_key_outdated", swapped.Code);

        var b2 = await _service.ReplaceAsync(_bob, NewKeyRequest());
        var stale = await Assert.ThrowsAsync<ConflictException>(() =>
            _service.EnsureMessageKeysAsync(_alice, _bob, Body(a.KeyId, b.KeyId)));
        Assert.Equal("recipient_key_changed", stale.Code);

        await _service.EnsureMessageKeysAsync(_alice, _bob, Body(a.KeyId, b2.KeyId));
    }

    [Fact]
    public async Task Message_in_the_old_format_is_rejected()
    {
        await _service.CreateAsync(_alice, NewKeyRequest());
        await _service.CreateAsync(_bob, NewKeyRequest());

        var error = await Assert.ThrowsAsync<BadRequestException>(() =>
            _service.EnsureMessageKeysAsync(_alice, _bob, Convert.ToBase64String(new byte[40])));
        Assert.Equal("invalid_encryption", error.Code);
    }
}
